<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Visual.Abstractions\Visual.Abstractions.csproj" />
    <ProjectReference Include="..\..\shared\Visual.Image\Visual.Image.csproj" />
    <ProjectReference Include="..\..\shared\Visual.IO\Visual.IO.csproj" />
    <ProjectReference Include="..\..\shared\Visual.Vision.Contracts\Visual.Vision.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\Visual.VisionBase\Visual.VisionBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

</Project>
